---
version: '3.4'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:6.1.1
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-kafka:6.1.1
    container_name: broker
    depends_on:
      - zookeeper
    ports:
      # "`-._,-'"`-._,-'"`-._,-'"`-._,-'"`-._,-'"`-._,-'"`-._,-'"`-._,-'"`-._,-
      # An important note about accessing Kafka from clients on other machines:
      # -----------------------------------------------------------------------
      #
      # The config used here exposes port 9092 for _external_ connections to the broker
      # i.e. those from _outside_ the docker network. This could be from the host machine
      # running docker, or maybe further afield if you've got a more complicated setup.
      # If the latter is true, you will need to change the value 'localhost' in
      # KAFKA_ADVERTISED_LISTENERS to one that is resolvable to the docker host from those
      # remote clients
      #
      # For connections _internal_ to the docker network, such as from other services
      # and components, use broker:29092.
      #
      # See https://rmoff.net/2018/08/02/kafka-listeners-explained/ for details
      # "`-._,-'"`-._,-'"`-._,-'"`-._,-'"`-._,-'"`-._,-'"`-._,-'"`-._,-'"`-._,-
      #
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 100

  schema-registry:
    image: confluentinc/cp-schema-registry:6.1.1
    container_name: schema-registry
    ports:
      - "8081:8081"
    depends_on:
      - broker
    environment:
      SCHEMA_REGISTRY_HOST_NAME: localhost
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: broker:29092

  hermes-frontend:
    build: ./hermes-frontend
    container_name: hermes-frontend
    ports:
      - "8080:8080"
    depends_on:
      - zookeeper
      - broker
    environment:
      MSK_ZK_CONNECT_STRING: "zookeeper:2181"
      MSK_KAFKA_BROKER_LIST: "broker:29092"
      KAFKA_SCHEMA_REGISTRY_URL: "http://schema-registry:8081"

  hermes-consumers:
    build: ./hermes-consumers
    container_name: hermes-consumers
    ports:
      - "8088:8080"
    depends_on:
      - zookeeper
      - broker
    environment:
      MSK_ZK_CONNECT_STRING: "zookeeper:2181"
      MSK_KAFKA_BROKER_LIST: "broker:29092"
      KAFKA_SCHEMA_REGISTRY_URL: "http://schema-registry:8081"

  hermes-management:
    build: ./hermes-management
    container_name: hermes-management
    ports:
      - "8090:8080"
    depends_on:
      - zookeeper
      - broker
    environment:
      MSK_ZK_CONNECT_STRING: "zookeeper:2181"
      KAFKA_SCHEMA_REGISTRY_URL: "http://schema-registry:8081"
      MSK_KAFKA_BROKER_LIST: "broker:29092"

  http-echo:
    image: mendhak/http-https-echo:18
    container_name: http-echo
    ports:
      - "8000:8080"