zookeeper:
  enabled: false


storage:
  clusters:
    -
      datacenter: dc
      clusterName: zk
      connectionString: ${MSK_ZK_CONNECT_STRING}

kafka:
  clusters:
    -
      datacenter: dc
      clusterName: primary
      connectionTimeout: 3000
      bootstrapKafkaServer: ${MSK_KAFKA_BROKER_LIST}

spring:
  jersey:
    type: filter

server:
  port: 8090

management:
  endpoints:
    web:
      base-path: /
  rest-template:
    connect-timeout: 2000
    read-timeout: 2000
  server:
    servlet:
      context-path: /
  health:
    periodSeconds: 30
    enabled: true

audit.enabled: false

topic:
  allowRemoval: true
  allowedTopicLabels: &ALLOWED_LABELS
    - internal
    - deprecated

topicOwnerCache:
  refreshRateInSeconds: 300 # 5 minutes

subscriptionOwnerCache:
  refreshRateInSeconds: 300

console:
  configurationLocation: console/config-local.json
  configurationType: classpath_resource
  topic:
    allowedTopicLabels: *ALLOWED_LABELS
